### ISSUE TITLE
Missing class error with 0.9

### ISSUE THREAD

**Issue by tmortagne** [schrepfler/jira-maven-plugin#132]
I get the following error when I try to use the jira plugin 0.9:

```
 [ERROR] Failed to execute goal net.sigmalab.maven.plugins:jira-maven-plugin:0.9:release-jira-version (default) on project xwiki-commons-tool-xar-integration-tests: Execution default of goal net.sigmalab.maven.plugins:jira-maven-plugin:0.9:release-jira-version failed: A required class was missing while executing net.sigmalab.maven.plugins:jira-maven-plugin:0.9:release-jira-version: io/atlassian/fugue/Suppliers
    [ERROR] -----------------------------------------------------
    [ERROR] realm =    plugin>net.sigmalab.maven.plugins:jira-maven-plugin:0.9
    [ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
    [ERROR] urls[0] = file:/home/hudsonagent/.m2/repository/net/sigmalab/maven/plugins/jira-maven-plugin/0.9/jira-maven-plugin-0.9.jar
    [ERROR] urls[1] = file:/home/hudsonagent/.m2/repository/com/atlassian/jira/jira-rest-java-client-core/5.2.1/jira-rest-java-client-core-5.2.1.jar
    [ERROR] urls[2] = file:/home/hudsonagent/.m2/repository/com/atlassian/jira/jira-rest-java-client-api/5.2.1/jira-rest-java-client-api-5.2.1.jar
    [ERROR] urls[3] = file:/home/hudsonagent/.m2/repository/com/atlassian/httpclient/atlassian-httpclient-api/2.0.0/atlassian-httpclient-api-2.0.0.jar
    [ERROR] urls[4] = file:/home/hudsonagent/.m2/repository/com/google/guava/guava/26.0-jre/guava-26.0-jre.jar
    [ERROR] urls[5] = file:/home/hudsonagent/.m2/repository/org/checkerframework/checker-qual/2.5.2/checker-qual-2.5.2.jar
    [ERROR] urls[6] = file:/home/hudsonagent/.m2/repository/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar
    [ERROR] urls[7] = file:/home/hudsonagent/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar
    [ERROR] urls[8] = file:/home/hudsonagent/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar
    [ERROR] urls[9] = file:/home/hudsonagent/.m2/repository/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar
    [ERROR] urls[10] = file:/home/hudsonagent/.m2/repository/com/sun/jersey/jersey-client/1.19/jersey-client-1.19.jar
    [ERROR] urls[11] = file:/home/hudsonagent/.m2/repository/com/sun/jersey/jersey-core/1.19/jersey-core-1.19.jar
    [ERROR] urls[12] = file:/home/hudsonagent/.m2/repository/javax/ws/rs/jsr311-api/1.1.1/jsr311-api-1.1.1.jar
    [ERROR] urls[13] = file:/home/hudsonagent/.m2/repository/com/sun/jersey/jersey-json/1.19/jersey-json-1.19.jar
    [ERROR] urls[14] = file:/home/hudsonagent/.m2/repository/org/codehaus/jettison/jettison/1.1/jettison-1.1.jar
    [ERROR] urls[15] = file:/home/hudsonagent/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.3-1/jaxb-impl-2.2.3-1.jar
    [ERROR] urls[16] = file:/home/hudsonagent/.m2/repository/javax/xml/bind/jaxb-api/2.2.2/jaxb-api-2.2.2.jar
    [ERROR] urls[17] = file:/home/hudsonagent/.m2/repository/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.jar
    [ERROR] urls[18] = file:/home/hudsonagent/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar
    [ERROR] urls[19] = file:/home/hudsonagent/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.2/jackson-core-asl-1.9.2.jar
    [ERROR] urls[20] = file:/home/hudsonagent/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.2/jackson-mapper-asl-1.9.2.jar
    [ERROR] urls[21] = file:/home/hudsonagent/.m2/repository/org/codehaus/jackson/jackson-jaxrs/1.9.2/jackson-jaxrs-1.9.2.jar
    [ERROR] urls[22] = file:/home/hudsonagent/.m2/repository/org/codehaus/jackson/jackson-xc/1.9.2/jackson-xc-1.9.2.jar
    [ERROR] urls[23] = file:/home/hudsonagent/.m2/repository/joda-time/joda-time/2.9.9/joda-time-2.9.9.jar
    [ERROR] urls[24] = file:/home/hudsonagent/.m2/repository/com/atlassian/sal/sal-api/3.0.7/sal-api-3.0.7.jar
    [ERROR] urls[25] = file:/home/hudsonagent/.m2/repository/com/atlassian/event/atlassian-event/3.0.0/atlassian-event-3.0.0.jar
    [ERROR] urls[26] = file:/home/hudsonagent/.m2/repository/org/springframework/spring-beans/4.1.7.RELEASE/spring-beans-4.1.7.RELEASE.jar
    [ERROR] urls[27] = file:/home/hudsonagent/.m2/repository/org/springframework/spring-core/4.1.7.RELEASE/spring-core-4.1.7.RELEASE.jar
    [ERROR] urls[28] = file:/home/hudsonagent/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
    [ERROR] urls[29] = file:/home/hudsonagent/.m2/repository/com/atlassian/httpclient/atlassian-httpclient-library/2.0.0/atlassian-httpclient-library-2.0.0.jar
    [ERROR] urls[30] = file:/home/hudsonagent/.m2/repository/org/apache/httpcomponents/httpasyncclient-cache/4.1.4/httpasyncclient-cache-4.1.4.jar
    [ERROR] urls[31] = file:/home/hudsonagent/.m2/repository/org/apache/httpcomponents/httpclient-cache/4.5.5/httpclient-cache-4.5.5.jar
    [ERROR] urls[32] = file:/home/hudsonagent/.m2/repository/org/apache/httpcomponents/httpclient/4.5.5/httpclient-4.5.5.jar
    [ERROR] urls[33] = file:/home/hudsonagent/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
    [ERROR] urls[34] = file:/home/hudsonagent/.m2/repository/org/apache/httpcomponents/httpasyncclient/4.1.4/httpasyncclient-4.1.4.jar
    [ERROR] urls[35] = file:/home/hudsonagent/.m2/repository/org/apache/httpcomponents/httpcore/4.4.10/httpcore-4.4.10.jar
    [ERROR] urls[36] = file:/home/hudsonagent/.m2/repository/org/apache/httpcomponents/httpcore-nio/4.4.10/httpcore-nio-4.4.10.jar
    [ERROR] urls[37] = file:/home/hudsonagent/.m2/repository/org/apache/httpcomponents/httpmime/4.5.5/httpmime-4.5.5.jar
    [ERROR] urls[38] = file:/home/hudsonagent/.m2/repository/io/atlassian/util/concurrent/atlassian-util-concurrent/4.0.1/atlassian-util-concurrent-4.0.1.jar
    [ERROR] urls[39] = file:/home/hudsonagent/.m2/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
    [ERROR] urls[40] = file:/home/hudsonagent/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
    [ERROR] urls[41] = file:/home/hudsonagent/.m2/repository/org/codehaus/plexus/plexus-utils/3.2.1/plexus-utils-3.2.1.jar
    [ERROR] urls[42] = file:/home/hudsonagent/.m2/repository/org/apache/maven/maven-builder-support/3.6.3/maven-builder-support-3.6.3.jar
    [ERROR] urls[43] = file:/home/hudsonagent/.m2/repository/org/apache/maven/resolver/maven-resolver-util/1.4.1/maven-resolver-util-1.4.1.jar
    [ERROR] urls[44] = file:/home/hudsonagent/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.2.1/maven-shared-utils-3.2.1.jar
    [ERROR] urls[45] = file:/home/hudsonagent/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar
    [ERROR] urls[46] = file:/home/hudsonagent/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.4/org.eclipse.sisu.inject-0.3.4.jar
    [ERROR] urls[47] = file:/home/hudsonagent/.m2/repository/com/google/inject/guice/4.2.1/guice-4.2.1-no_aop.jar
    [ERROR] urls[48] = file:/home/hudsonagent/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
    [ERROR] urls[49] = file:/home/hudsonagent/.m2/repository/org/codehaus/plexus/plexus-component-annotations/2.1.0/plexus-component-annotations-2.1.0.jar
    [ERROR] urls[50] = file:/home/hudsonagent/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.25/plexus-interpolation-1.25.jar
    [ERROR] urls[51] = file:/home/hudsonagent/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.4/plexus-sec-dispatcher-1.4.jar
    [ERROR] urls[52] = file:/home/hudsonagent/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
    [ERROR] Number of foreign imports: 1
    [ERROR] import: Entry[import  from realm ClassRealm[project>org.xwiki.commons:xwiki-commons:12.8-rc-1, parent: ClassRealm[maven.api, parent: null]]]
```

Like in https://github.com/schrepfler/jira-maven-plugin/issues/59 it sounds like bad or missing dependency (the one which contains io.atlassian.fugue.Suppliers) in the plugin.

Maven verison: 3.6.3
Java verison: 1.8

**Comment by dgrierso** [comment]
@schrepfler : looks like the issue was introduced by https://github.com/schrepfler/jira-maven-plugin/commit/bf97de30532f82c14add4965dc080d4553f0dd5b with the removal of the fugue dependency.

@tmortagne : I've just pushed this back into `develop` - can you retry with a build from that?

**Comment by schrepfler** [comment]
Thanks for the report @tmortagne, we could probably use some integration tests not just unit tests. @tmortagne can you add the full stack trace where we can see the error calling for `io.atlassian.fugue.Suppliers`?
I would have thought jira-rest-java-client-core would import it if it would need it so would like to understand what uses this dependency.

**Comment by schrepfler** [comment]
It seems my selective memory wiped out everything from 2018. https://github.com/schrepfler/jira-maven-plugin/issues/59 Thanks for reminding me @tmortagne

**Comment by dgrierso** [comment]
I should probably have numbered the next version as 0.9.1-SNAPSHOT. 

Do we have the capability to publish snapshot versions?

**Comment by schrepfler** [comment]
> I should probably have numbered the next version as 0.9.1-SNAPSHOT. 
> 
> Do we have the capability to publish snapshot versions?
I think not at the moment. I'm trying to do more of a trunk-based-development release and release process automation. I'm out on a run, when I come back home I'll push the jar to nexus.

**Comment by schrepfler** [comment]
I've published the artefact to https://oss.sonatype.org/#nexus-search;quick~jira-maven-plugin but not seeing it still on maven central. Thanks for raising the issue, good to see someone is still using the plugin and we have some maintainers still around. Glad everyone's OK with the pandemic and all. Stay safe!

**Comment by schrepfler** [comment]
The artefact is now on maven central, please test and confirm if working again @tmortagne.

**Comment by dgrierso** [comment]
Issue is still presenting in version 0.9.1 of the plugin ... apologies this fix last night wasn't properly tested & was an assumed fix.

On attempting to use the plugin this morning within another maven project I get the following:

```
...
[INFO]
[INFO] --- jira-maven-plugin:0.9.1:create-new-jira-version (default) @ confluence-user-count ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.152 s
[INFO] Finished at: 2020-09-23T10:08:32+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.sigmalab.maven.plugins:jira-maven-plugin:0.9.1:create-new-jira-version (default) on project confluence-user-count: Execution default of goal net.sigmalab.maven.plugins:jira-maven-plugin:0.9.1:create-new-jira-version failed: A required class was missing while executing net.sigmalab.maven.plugins:jira-maven-plugin:0.9.1:create-new-jira-version: io/atlassian/fugue/Suppliers
[ERROR] -----------------------------------------------------
...
```

**Comment by dgrierso** [comment]
Okay - fixed this properly now (and integration tested with a real Jira service) as well.

Looks like Atlassian have updated the groupId associated with fugue and moved the version on significantly as well. The fugue package is a dependency of the atlassian-jira-rest-client package which has had its version moved on by the `dependabot`.

Unfortunately, as @schrepfler says, unit tests won't pick this up as the REST client is mocked out and only integration testing by actually using the plugin would identify it.

I've just committed an updated version to `develop` and submitted pull request 134 to get this onto master.

----
As a workaround, if you _really_ want to use version 0.9 or 0.9.1 then you need to add a dependency to the plugin configuration:

```
      <dependencies>
        <depenency>
          <groupId>io.atlassian.fugue</groupId>
          <artifactId>fugue</artifactId>
          <version>4.7.2</version>
        </dependency>
      </dependencies>
```
----

Apologies for this.

**Comment by tmortagne** [comment]
You were faster than me @dgrierso. I confirm that I get the same error than with 0.9 when testing with 0.9.1.

Here is a more detailed version than in my first message:

```
$ mvn install -e
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< org.xwiki.contrib:parent-commons >------------------
[INFO] Building parent-commons 43.0
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ parent-commons ---
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ parent-commons ---
[INFO] Installing /media/DATA/projects/jira-maven-plugin/pom.xml to /home/tmortagne/.m2/repository/org/xwiki/contrib/parent-commons/43.0/parent-commons-43.0.pom
[INFO] 
[INFO] --- jira-maven-plugin:0.9.1:create-new-jira-version (default) @ parent-commons ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.449 s
[INFO] Finished at: 2020-09-23T12:17:56+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.sigmalab.maven.plugins:jira-maven-plugin:0.9.1:create-new-jira-version (default) on project parent-commons: Execution default of goal net.sigmalab.maven.plugins:jira-maven-plugin:0.9.1:create-new-jira-version failed: A required class was missing while executing net.sigmalab.maven.plugins:jira-maven-plugin:0.9.1:create-new-jira-version: io/atlassian/fugue/Suppliers
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>net.sigmalab.maven.plugins:jira-maven-plugin:0.9.1
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/tmortagne/.m2/repository/net/sigmalab/maven/plugins/jira-maven-plugin/0.9.1/jira-maven-plugin-0.9.1.jar
[ERROR] urls[1] = file:/home/tmortagne/.m2/repository/com/atlassian/jira/jira-rest-java-client-core/5.2.1/jira-rest-java-client-core-5.2.1.jar
[ERROR] urls[2] = file:/home/tmortagne/.m2/repository/com/atlassian/jira/jira-rest-java-client-api/5.2.1/jira-rest-java-client-api-5.2.1.jar
[ERROR] urls[3] = file:/home/tmortagne/.m2/repository/com/atlassian/httpclient/atlassian-httpclient-api/2.0.0/atlassian-httpclient-api-2.0.0.jar
[ERROR] urls[4] = file:/home/tmortagne/.m2/repository/com/google/guava/guava/26.0-jre/guava-26.0-jre.jar
[ERROR] urls[5] = file:/home/tmortagne/.m2/repository/org/checkerframework/checker-qual/2.5.2/checker-qual-2.5.2.jar
[ERROR] urls[6] = file:/home/tmortagne/.m2/repository/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar
[ERROR] urls[7] = file:/home/tmortagne/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar
[ERROR] urls[8] = file:/home/tmortagne/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar
[ERROR] urls[9] = file:/home/tmortagne/.m2/repository/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar
[ERROR] urls[10] = file:/home/tmortagne/.m2/repository/com/sun/jersey/jersey-client/1.19/jersey-client-1.19.jar
[ERROR] urls[11] = file:/home/tmortagne/.m2/repository/com/sun/jersey/jersey-core/1.19/jersey-core-1.19.jar
[ERROR] urls[12] = file:/home/tmortagne/.m2/repository/javax/ws/rs/jsr311-api/1.1.1/jsr311-api-1.1.1.jar
[ERROR] urls[13] = file:/home/tmortagne/.m2/repository/com/sun/jersey/jersey-json/1.19/jersey-json-1.19.jar
[ERROR] urls[14] = file:/home/tmortagne/.m2/repository/org/codehaus/jettison/jettison/1.1/jettison-1.1.jar
[ERROR] urls[15] = file:/home/tmortagne/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.3-1/jaxb-impl-2.2.3-1.jar
[ERROR] urls[16] = file:/home/tmortagne/.m2/repository/javax/xml/bind/jaxb-api/2.2.2/jaxb-api-2.2.2.jar
[ERROR] urls[17] = file:/home/tmortagne/.m2/repository/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.jar
[ERROR] urls[18] = file:/home/tmortagne/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar
[ERROR] urls[19] = file:/home/tmortagne/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.2/jackson-core-asl-1.9.2.jar
[ERROR] urls[20] = file:/home/tmortagne/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.2/jackson-mapper-asl-1.9.2.jar
[ERROR] urls[21] = file:/home/tmortagne/.m2/repository/org/codehaus/jackson/jackson-jaxrs/1.9.2/jackson-jaxrs-1.9.2.jar
[ERROR] urls[22] = file:/home/tmortagne/.m2/repository/org/codehaus/jackson/jackson-xc/1.9.2/jackson-xc-1.9.2.jar
[ERROR] urls[23] = file:/home/tmortagne/.m2/repository/joda-time/joda-time/2.9.9/joda-time-2.9.9.jar
[ERROR] urls[24] = file:/home/tmortagne/.m2/repository/com/atlassian/sal/sal-api/3.0.7/sal-api-3.0.7.jar
[ERROR] urls[25] = file:/home/tmortagne/.m2/repository/com/atlassian/event/atlassian-event/3.0.0/atlassian-event-3.0.0.jar
[ERROR] urls[26] = file:/home/tmortagne/.m2/repository/org/springframework/spring-beans/4.1.7.RELEASE/spring-beans-4.1.7.RELEASE.jar
[ERROR] urls[27] = file:/home/tmortagne/.m2/repository/org/springframework/spring-core/4.1.7.RELEASE/spring-core-4.1.7.RELEASE.jar
[ERROR] urls[28] = file:/home/tmortagne/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
[ERROR] urls[29] = file:/home/tmortagne/.m2/repository/com/atlassian/httpclient/atlassian-httpclient-library/2.0.0/atlassian-httpclient-library-2.0.0.jar
[ERROR] urls[30] = file:/home/tmortagne/.m2/repository/org/apache/httpcomponents/httpasyncclient-cache/4.1.4/httpasyncclient-cache-4.1.4.jar
[ERROR] urls[31] = file:/home/tmortagne/.m2/repository/org/apache/httpcomponents/httpclient-cache/4.5.5/httpclient-cache-4.5.5.jar
[ERROR] urls[32] = file:/home/tmortagne/.m2/repository/org/apache/httpcomponents/httpclient/4.5.5/httpclient-4.5.5.jar
[ERROR] urls[33] = file:/home/tmortagne/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
[ERROR] urls[34] = file:/home/tmortagne/.m2/repository/org/apache/httpcomponents/httpasyncclient/4.1.4/httpasyncclient-4.1.4.jar
[ERROR] urls[35] = file:/home/tmortagne/.m2/repository/org/apache/httpcomponents/httpcore/4.4.10/httpcore-4.4.10.jar
[ERROR] urls[36] = file:/home/tmortagne/.m2/repository/org/apache/httpcomponents/httpcore-nio/4.4.10/httpcore-nio-4.4.10.jar
[ERROR] urls[37] = file:/home/tmortagne/.m2/repository/org/apache/httpcomponents/httpmime/4.5.5/httpmime-4.5.5.jar
[ERROR] urls[38] = file:/home/tmortagne/.m2/repository/io/atlassian/util/concurrent/atlassian-util-concurrent/4.0.1/atlassian-util-concurrent-4.0.1.jar
[ERROR] urls[39] = file:/home/tmortagne/.m2/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
[ERROR] urls[40] = file:/home/tmortagne/.m2/repository/com/atlassian/fugue/fugue/2.7.0/fugue-2.7.0.jar
[ERROR] urls[41] = file:/home/tmortagne/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[42] = file:/home/tmortagne/.m2/repository/org/codehaus/plexus/plexus-utils/3.2.1/plexus-utils-3.2.1.jar
[ERROR] urls[43] = file:/home/tmortagne/.m2/repository/org/apache/maven/maven-builder-support/3.6.3/maven-builder-support-3.6.3.jar
[ERROR] urls[44] = file:/home/tmortagne/.m2/repository/org/apache/maven/resolver/maven-resolver-util/1.4.1/maven-resolver-util-1.4.1.jar
[ERROR] urls[45] = file:/home/tmortagne/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.2.1/maven-shared-utils-3.2.1.jar
[ERROR] urls[46] = file:/home/tmortagne/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar
[ERROR] urls[47] = file:/home/tmortagne/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.4/org.eclipse.sisu.inject-0.3.4.jar
[ERROR] urls[48] = file:/home/tmortagne/.m2/repository/com/google/inject/guice/4.2.1/guice-4.2.1-no_aop.jar
[ERROR] urls[49] = file:/home/tmortagne/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[50] = file:/home/tmortagne/.m2/repository/org/codehaus/plexus/plexus-component-annotations/2.1.0/plexus-component-annotations-2.1.0.jar
[ERROR] urls[51] = file:/home/tmortagne/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.25/plexus-interpolation-1.25.jar
[ERROR] urls[52] = file:/home/tmortagne/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.4/plexus-sec-dispatcher-1.4.jar
[ERROR] urls[53] = file:/home/tmortagne/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] : io.atlassian.fugue.Suppliers
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.sigmalab.maven.plugins:jira-maven-plugin:0.9.1:create-new-jira-version (default) on project parent-commons: Execution default of goal net.sigmalab.maven.plugins:jira-maven-plugin:0.9.1:create-new-jira-version failed: A required class was missing while executing net.sigmalab.maven.plugins:jira-maven-plugin:0.9.1:create-new-jira-version: io/atlassian/fugue/Suppliers
-----------------------------------------------------
realm =    plugin>net.sigmalab.maven.plugins:jira-maven-plugin:0.9.1
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/home/tmortagne/.m2/repository/net/sigmalab/maven/plugins/jira-maven-plugin/0.9.1/jira-maven-plugin-0.9.1.jar
urls[1] = file:/home/tmortagne/.m2/repository/com/atlassian/jira/jira-rest-java-client-core/5.2.1/jira-rest-java-client-core-5.2.1.jar
urls[2] = file:/home/tmortagne/.m2/repository/com/atlassian/jira/jira-rest-java-client-api/5.2.1/jira-rest-java-client-api-5.2.1.jar
urls[3] = file:/home/tmortagne/.m2/repository/com/atlassian/httpclient/atlassian-httpclient-api/2.0.0/atlassian-httpclient-api-2.0.0.jar
urls[4] = file:/home/tmortagne/.m2/repository/com/google/guava/guava/26.0-jre/guava-26.0-jre.jar
urls[5] = file:/home/tmortagne/.m2/repository/org/checkerframework/checker-qual/2.5.2/checker-qual-2.5.2.jar
urls[6] = file:/home/tmortagne/.m2/repository/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar
urls[7] = file:/home/tmortagne/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar
urls[8] = file:/home/tmortagne/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar
urls[9] = file:/home/tmortagne/.m2/repository/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar
urls[10] = file:/home/tmortagne/.m2/repository/com/sun/jersey/jersey-client/1.19/jersey-client-1.19.jar
urls[11] = file:/home/tmortagne/.m2/repository/com/sun/jersey/jersey-core/1.19/jersey-core-1.19.jar
urls[12] = file:/home/tmortagne/.m2/repository/javax/ws/rs/jsr311-api/1.1.1/jsr311-api-1.1.1.jar
urls[13] = file:/home/tmortagne/.m2/repository/com/sun/jersey/jersey-json/1.19/jersey-json-1.19.jar
urls[14] = file:/home/tmortagne/.m2/repository/org/codehaus/jettison/jettison/1.1/jettison-1.1.jar
urls[15] = file:/home/tmortagne/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.3-1/jaxb-impl-2.2.3-1.jar
urls[16] = file:/home/tmortagne/.m2/repository/javax/xml/bind/jaxb-api/2.2.2/jaxb-api-2.2.2.jar
urls[17] = file:/home/tmortagne/.m2/repository/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.jar
urls[18] = file:/home/tmortagne/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar
urls[19] = file:/home/tmortagne/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.2/jackson-core-asl-1.9.2.jar
urls[20] = file:/home/tmortagne/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.2/jackson-mapper-asl-1.9.2.jar
urls[21] = file:/home/tmortagne/.m2/repository/org/codehaus/jackson/jackson-jaxrs/1.9.2/jackson-jaxrs-1.9.2.jar
urls[22] = file:/home/tmortagne/.m2/repository/org/codehaus/jackson/jackson-xc/1.9.2/jackson-xc-1.9.2.jar
urls[23] = file:/home/tmortagne/.m2/repository/joda-time/joda-time/2.9.9/joda-time-2.9.9.jar
urls[24] = file:/home/tmortagne/.m2/repository/com/atlassian/sal/sal-api/3.0.7/sal-api-3.0.7.jar
urls[25] = file:/home/tmortagne/.m2/repository/com/atlassian/event/atlassian-event/3.0.0/atlassian-event-3.0.0.jar
urls[26] = file:/home/tmortagne/.m2/repository/org/springframework/spring-beans/4.1.7.RELEASE/spring-beans-4.1.7.RELEASE.jar
urls[27] = file:/home/tmortagne/.m2/repository/org/springframework/spring-core/4.1.7.RELEASE/spring-core-4.1.7.RELEASE.jar
urls[28] = file:/home/tmortagne/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
urls[29] = file:/home/tmortagne/.m2/repository/com/atlassian/httpclient/atlassian-httpclient-library/2.0.0/atlassian-httpclient-library-2.0.0.jar
urls[30] = file:/home/tmortagne/.m2/repository/org/apache/httpcomponents/httpasyncclient-cache/4.1.4/httpasyncclient-cache-4.1.4.jar
urls[31] = file:/home/tmortagne/.m2/repository/org/apache/httpcomponents/httpclient-cache/4.5.5/httpclient-cache-4.5.5.jar
urls[32] = file:/home/tmortagne/.m2/repository/org/apache/httpcomponents/httpclient/4.5.5/httpclient-4.5.5.jar
urls[33] = file:/home/tmortagne/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
urls[34] = file:/home/tmortagne/.m2/repository/org/apache/httpcomponents/httpasyncclient/4.1.4/httpasyncclient-4.1.4.jar
urls[35] = file:/home/tmortagne/.m2/repository/org/apache/httpcomponents/httpcore/4.4.10/httpcore-4.4.10.jar
urls[36] = file:/home/tmortagne/.m2/repository/org/apache/httpcomponents/httpcore-nio/4.4.10/httpcore-nio-4.4.10.jar
urls[37] = file:/home/tmortagne/.m2/repository/org/apache/httpcomponents/httpmime/4.5.5/httpmime-4.5.5.jar
urls[38] = file:/home/tmortagne/.m2/repository/io/atlassian/util/concurrent/atlassian-util-concurrent/4.0.1/atlassian-util-concurrent-4.0.1.jar
urls[39] = file:/home/tmortagne/.m2/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
urls[40] = file:/home/tmortagne/.m2/repository/com/atlassian/fugue/fugue/2.7.0/fugue-2.7.0.jar
urls[41] = file:/home/tmortagne/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
urls[42] = file:/home/tmortagne/.m2/repository/org/codehaus/plexus/plexus-utils/3.2.1/plexus-utils-3.2.1.jar
urls[43] = file:/home/tmortagne/.m2/repository/org/apache/maven/maven-builder-support/3.6.3/maven-builder-support-3.6.3.jar
urls[44] = file:/home/tmortagne/.m2/repository/org/apache/maven/resolver/maven-resolver-util/1.4.1/maven-resolver-util-1.4.1.jar
urls[45] = file:/home/tmortagne/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.2.1/maven-shared-utils-3.2.1.jar
urls[46] = file:/home/tmortagne/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar
urls[47] = file:/home/tmortagne/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.4/org.eclipse.sisu.inject-0.3.4.jar
urls[48] = file:/home/tmortagne/.m2/repository/com/google/inject/guice/4.2.1/guice-4.2.1-no_aop.jar
urls[49] = file:/home/tmortagne/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
urls[50] = file:/home/tmortagne/.m2/repository/org/codehaus/plexus/plexus-component-annotations/2.1.0/plexus-component-annotations-2.1.0.jar
urls[51] = file:/home/tmortagne/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.25/plexus-interpolation-1.25.jar
urls[52] = file:/home/tmortagne/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.4/plexus-sec-dispatcher-1.4.jar
urls[53] = file:/home/tmortagne/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal net.sigmalab.maven.plugins:jira-maven-plugin:0.9.1:create-new-jira-version failed: A required class was missing while executing net.sigmalab.maven.plugins:jira-maven-plugin:0.9.1:create-new-jira-version: io/atlassian/fugue/Suppliers
-----------------------------------------------------
realm =    plugin>net.sigmalab.maven.plugins:jira-maven-plugin:0.9.1
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/home/tmortagne/.m2/repository/net/sigmalab/maven/plugins/jira-maven-plugin/0.9.1/jira-maven-plugin-0.9.1.jar
urls[1] = file:/home/tmortagne/.m2/repository/com/atlassian/jira/jira-rest-java-client-core/5.2.1/jira-rest-java-client-core-5.2.1.jar
urls[2] = file:/home/tmortagne/.m2/repository/com/atlassian/jira/jira-rest-java-client-api/5.2.1/jira-rest-java-client-api-5.2.1.jar
urls[3] = file:/home/tmortagne/.m2/repository/com/atlassian/httpclient/atlassian-httpclient-api/2.0.0/atlassian-httpclient-api-2.0.0.jar
urls[4] = file:/home/tmortagne/.m2/repository/com/google/guava/guava/26.0-jre/guava-26.0-jre.jar
urls[5] = file:/home/tmortagne/.m2/repository/org/checkerframework/checker-qual/2.5.2/checker-qual-2.5.2.jar
urls[6] = file:/home/tmortagne/.m2/repository/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar
urls[7] = file:/home/tmortagne/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar
urls[8] = file:/home/tmortagne/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar
urls[9] = file:/home/tmortagne/.m2/repository/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar
urls[10] = file:/home/tmortagne/.m2/repository/com/sun/jersey/jersey-client/1.19/jersey-client-1.19.jar
urls[11] = file:/home/tmortagne/.m2/repository/com/sun/jersey/jersey-core/1.19/jersey-core-1.19.jar
urls[12] = file:/home/tmortagne/.m2/repository/javax/ws/rs/jsr311-api/1.1.1/jsr311-api-1.1.1.jar
urls[13] = file:/home/tmortagne/.m2/repository/com/sun/jersey/jersey-json/1.19/jersey-json-1.19.jar
urls[14] = file:/home/tmortagne/.m2/repository/org/codehaus/jettison/jettison/1.1/jettison-1.1.jar
urls[15] = file:/home/tmortagne/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.3-1/jaxb-impl-2.2.3-1.jar
urls[16] = file:/home/tmortagne/.m2/repository/javax/xml/bind/jaxb-api/2.2.2/jaxb-api-2.2.2.jar
urls[17] = file:/home/tmortagne/.m2/repository/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.jar
urls[18] = file:/home/tmortagne/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar
urls[19] = file:/home/tmortagne/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.2/jackson-core-asl-1.9.2.jar
urls[20] = file:/home/tmortagne/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.2/jackson-mapper-asl-1.9.2.jar
urls[21] = file:/home/tmortagne/.m2/repository/org/codehaus/jackson/jackson-jaxrs/1.9.2/jackson-jaxrs-1.9.2.jar
urls[22] = file:/home/tmortagne/.m2/repository/org/codehaus/jackson/jackson-xc/1.9.2/jackson-xc-1.9.2.jar
urls[23] = file:/home/tmortagne/.m2/repository/joda-time/joda-time/2.9.9/joda-time-2.9.9.jar
urls[24] = file:/home/tmortagne/.m2/repository/com/atlassian/sal/sal-api/3.0.7/sal-api-3.0.7.jar
urls[25] = file:/home/tmortagne/.m2/repository/com/atlassian/event/atlassian-event/3.0.0/atlassian-event-3.0.0.jar
urls[26] = file:/home/tmortagne/.m2/repository/org/springframework/spring-beans/4.1.7.RELEASE/spring-beans-4.1.7.RELEASE.jar
urls[27] = file:/home/tmortagne/.m2/repository/org/springframework/spring-core/4.1.7.RELEASE/spring-core-4.1.7.RELEASE.jar
urls[28] = file:/home/tmortagne/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
urls[29] = file:/home/tmortagne/.m2/repository/com/atlassian/httpclient/atlassian-httpclient-library/2.0.0/atlassian-httpclient-library-2.0.0.jar
urls[30] = file:/home/tmortagne/.m2/repository/org/apache/httpcomponents/httpasyncclient-cache/4.1.4/httpasyncclient-cache-4.1.4.jar
urls[31] = file:/home/tmortagne/.m2/repository/org/apache/httpcomponents/httpclient-cache/4.5.5/httpclient-cache-4.5.5.jar
urls[32] = file:/home/tmortagne/.m2/repository/org/apache/httpcomponents/httpclient/4.5.5/httpclient-4.5.5.jar
urls[33] = file:/home/tmortagne/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
urls[34] = file:/home/tmortagne/.m2/repository/org/apache/httpcomponents/httpasyncclient/4.1.4/httpasyncclient-4.1.4.jar
urls[35] = file:/home/tmortagne/.m2/repository/org/apache/httpcomponents/httpcore/4.4.10/httpcore-4.4.10.jar
urls[36] = file:/home/tmortagne/.m2/repository/org/apache/httpcomponents/httpcore-nio/4.4.10/httpcore-nio-4.4.10.jar
urls[37] = file:/home/tmortagne/.m2/repository/org/apache/httpcomponents/httpmime/4.5.5/httpmime-4.5.5.jar
urls[38] = file:/home/tmortagne/.m2/repository/io/atlassian/util/concurrent/atlassian-util-concurrent/4.0.1/atlassian-util-concurrent-4.0.1.jar
urls[39] = file:/home/tmortagne/.m2/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
urls[40] = file:/home/tmortagne/.m2/repository/com/atlassian/fugue/fugue/2.7.0/fugue-2.7.0.jar
urls[41] = file:/home/tmortagne/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
urls[42] = file:/home/tmortagne/.m2/repository/org/codehaus/plexus/plexus-utils/3.2.1/plexus-utils-3.2.1.jar
urls[43] = file:/home/tmortagne/.m2/repository/org/apache/maven/maven-builder-support/3.6.3/maven-builder-support-3.6.3.jar
urls[44] = file:/home/tmortagne/.m2/repository/org/apache/maven/resolver/maven-resolver-util/1.4.1/maven-resolver-util-1.4.1.jar
urls[45] = file:/home/tmortagne/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.2.1/maven-shared-utils-3.2.1.jar
urls[46] = file:/home/tmortagne/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar
urls[47] = file:/home/tmortagne/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.4/org.eclipse.sisu.inject-0.3.4.jar
urls[48] = file:/home/tmortagne/.m2/repository/com/google/inject/guice/4.2.1/guice-4.2.1-no_aop.jar
urls[49] = file:/home/tmortagne/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
urls[50] = file:/home/tmortagne/.m2/repository/org/codehaus/plexus/plexus-component-annotations/2.1.0/plexus-component-annotations-2.1.0.jar
urls[51] = file:/home/tmortagne/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.25/plexus-interpolation-1.25.jar
urls[52] = file:/home/tmortagne/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.4/plexus-sec-dispatcher-1.4.jar
urls[53] = file:/home/tmortagne/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.PluginContainerException: A required class was missing while executing net.sigmalab.maven.plugins:jira-maven-plugin:0.9.1:create-new-jira-version: io/atlassian/fugue/Suppliers
-----------------------------------------------------
realm =    plugin>net.sigmalab.maven.plugins:jira-maven-plugin:0.9.1
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/home/tmortagne/.m2/repository/net/sigmalab/maven/plugins/jira-maven-plugin/0.9.1/jira-maven-plugin-0.9.1.jar
urls[1] = file:/home/tmortagne/.m2/repository/com/atlassian/jira/jira-rest-java-client-core/5.2.1/jira-rest-java-client-core-5.2.1.jar
urls[2] = file:/home/tmortagne/.m2/repository/com/atlassian/jira/jira-rest-java-client-api/5.2.1/jira-rest-java-client-api-5.2.1.jar
urls[3] = file:/home/tmortagne/.m2/repository/com/atlassian/httpclient/atlassian-httpclient-api/2.0.0/atlassian-httpclient-api-2.0.0.jar
urls[4] = file:/home/tmortagne/.m2/repository/com/google/guava/guava/26.0-jre/guava-26.0-jre.jar
urls[5] = file:/home/tmortagne/.m2/repository/org/checkerframework/checker-qual/2.5.2/checker-qual-2.5.2.jar
urls[6] = file:/home/tmortagne/.m2/repository/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar
urls[7] = file:/home/tmortagne/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar
urls[8] = file:/home/tmortagne/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar
urls[9] = file:/home/tmortagne/.m2/repository/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar
urls[10] = file:/home/tmortagne/.m2/repository/com/sun/jersey/jersey-client/1.19/jersey-client-1.19.jar
urls[11] = file:/home/tmortagne/.m2/repository/com/sun/jersey/jersey-core/1.19/jersey-core-1.19.jar
urls[12] = file:/home/tmortagne/.m2/repository/javax/ws/rs/jsr311-api/1.1.1/jsr311-api-1.1.1.jar
urls[13] = file:/home/tmortagne/.m2/repository/com/sun/jersey/jersey-json/1.19/jersey-json-1.19.jar
urls[14] = file:/home/tmortagne/.m2/repository/org/codehaus/jettison/jettison/1.1/jettison-1.1.jar
urls[15] = file:/home/tmortagne/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.3-1/jaxb-impl-2.2.3-1.jar
urls[16] = file:/home/tmortagne/.m2/repository/javax/xml/bind/jaxb-api/2.2.2/jaxb-api-2.2.2.jar
urls[17] = file:/home/tmortagne/.m2/repository/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.jar
urls[18] = file:/home/tmortagne/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar
urls[19] = file:/home/tmortagne/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.2/jackson-core-asl-1.9.2.jar
urls[20] = file:/home/tmortagne/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.2/jackson-mapper-asl-1.9.2.jar
urls[21] = file:/home/tmortagne/.m2/repository/org/codehaus/jackson/jackson-jaxrs/1.9.2/jackson-jaxrs-1.9.2.jar
urls[22] = file:/home/tmortagne/.m2/repository/org/codehaus/jackson/jackson-xc/1.9.2/jackson-xc-1.9.2.jar
urls[23] = file:/home/tmortagne/.m2/repository/joda-time/joda-time/2.9.9/joda-time-2.9.9.jar
urls[24] = file:/home/tmortagne/.m2/repository/com/atlassian/sal/sal-api/3.0.7/sal-api-3.0.7.jar
urls[25] = file:/home/tmortagne/.m2/repository/com/atlassian/event/atlassian-event/3.0.0/atlassian-event-3.0.0.jar
urls[26] = file:/home/tmortagne/.m2/repository/org/springframework/spring-beans/4.1.7.RELEASE/spring-beans-4.1.7.RELEASE.jar
urls[27] = file:/home/tmortagne/.m2/repository/org/springframework/spring-core/4.1.7.RELEASE/spring-core-4.1.7.RELEASE.jar
urls[28] = file:/home/tmortagne/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
urls[29] = file:/home/tmortagne/.m2/repository/com/atlassian/httpclient/atlassian-httpclient-library/2.0.0/atlassian-httpclient-library-2.0.0.jar
urls[30] = file:/home/tmortagne/.m2/repository/org/apache/httpcomponents/httpasyncclient-cache/4.1.4/httpasyncclient-cache-4.1.4.jar
urls[31] = file:/home/tmortagne/.m2/repository/org/apache/httpcomponents/httpclient-cache/4.5.5/httpclient-cache-4.5.5.jar
urls[32] = file:/home/tmortagne/.m2/repository/org/apache/httpcomponents/httpclient/4.5.5/httpclient-4.5.5.jar
urls[33] = file:/home/tmortagne/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
urls[34] = file:/home/tmortagne/.m2/repository/org/apache/httpcomponents/httpasyncclient/4.1.4/httpasyncclient-4.1.4.jar
urls[35] = file:/home/tmortagne/.m2/repository/org/apache/httpcomponents/httpcore/4.4.10/httpcore-4.4.10.jar
urls[36] = file:/home/tmortagne/.m2/repository/org/apache/httpcomponents/httpcore-nio/4.4.10/httpcore-nio-4.4.10.jar
urls[37] = file:/home/tmortagne/.m2/repository/org/apache/httpcomponents/httpmime/4.5.5/httpmime-4.5.5.jar
urls[38] = file:/home/tmortagne/.m2/repository/io/atlassian/util/concurrent/atlassian-util-concurrent/4.0.1/atlassian-util-concurrent-4.0.1.jar
urls[39] = file:/home/tmortagne/.m2/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
urls[40] = file:/home/tmortagne/.m2/repository/com/atlassian/fugue/fugue/2.7.0/fugue-2.7.0.jar
urls[41] = file:/home/tmortagne/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
urls[42] = file:/home/tmortagne/.m2/repository/org/codehaus/plexus/plexus-utils/3.2.1/plexus-utils-3.2.1.jar
urls[43] = file:/home/tmortagne/.m2/repository/org/apache/maven/maven-builder-support/3.6.3/maven-builder-support-3.6.3.jar
urls[44] = file:/home/tmortagne/.m2/repository/org/apache/maven/resolver/maven-resolver-util/1.4.1/maven-resolver-util-1.4.1.jar
urls[45] = file:/home/tmortagne/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.2.1/maven-shared-utils-3.2.1.jar
urls[46] = file:/home/tmortagne/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar
urls[47] = file:/home/tmortagne/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.4/org.eclipse.sisu.inject-0.3.4.jar
urls[48] = file:/home/tmortagne/.m2/repository/com/google/inject/guice/4.2.1/guice-4.2.1-no_aop.jar
urls[49] = file:/home/tmortagne/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
urls[50] = file:/home/tmortagne/.m2/repository/org/codehaus/plexus/plexus-component-annotations/2.1.0/plexus-component-annotations-2.1.0.jar
urls[51] = file:/home/tmortagne/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.25/plexus-interpolation-1.25.jar
urls[52] = file:/home/tmortagne/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.4/plexus-sec-dispatcher-1.4.jar
urls[53] = file:/home/tmortagne/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:169)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.lang.NoClassDefFoundError: io/atlassian/fugue/Suppliers
    at com.atlassian.httpclient.apache.httpcomponents.ApacheAsyncHttpClient.<clinit> (ApacheAsyncHttpClient.java:80)
    at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClientFactory.doCreate (DefaultHttpClientFactory.java:61)
    at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClientFactory.create (DefaultHttpClientFactory.java:36)
    at com.atlassian.jira.rest.client.internal.async.AsynchronousHttpClientFactory.createClient (AsynchronousHttpClientFactory.java:65)
    at com.atlassian.jira.rest.client.internal.async.AsynchronousJiraRestClientFactory.create (AsynchronousJiraRestClientFactory.java:36)
    at com.atlassian.jira.rest.client.internal.async.AsynchronousJiraRestClientFactory.createWithBasicHttpAuthentication (AsynchronousJiraRestClientFactory.java:42)
    at net.sigmalab.maven.plugin.jira.AbstractJiraMojo.execute (AbstractJiraMojo.java:184)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.lang.ClassNotFoundException: io.atlassian.fugue.Suppliers
    at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass (SelfFirstStrategy.java:50)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass (ClassRealm.java:271)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass (ClassRealm.java:247)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass (ClassRealm.java:239)
    at com.atlassian.httpclient.apache.httpcomponents.ApacheAsyncHttpClient.<clinit> (ApacheAsyncHttpClient.java:80)
    at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClientFactory.doCreate (DefaultHttpClientFactory.java:61)
    at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClientFactory.create (DefaultHttpClientFactory.java:36)
    at com.atlassian.jira.rest.client.internal.async.AsynchronousHttpClientFactory.createClient (AsynchronousHttpClientFactory.java:65)
    at com.atlassian.jira.rest.client.internal.async.AsynchronousJiraRestClientFactory.create (AsynchronousJiraRestClientFactory.java:36)
    at com.atlassian.jira.rest.client.internal.async.AsynchronousJiraRestClientFactory.createWithBasicHttpAuthentication (AsynchronousJiraRestClientFactory.java:42)
    at net.sigmalab.maven.plugin.jira.AbstractJiraMojo.execute (AbstractJiraMojo.java:184)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
```

Here is the pom I used for the test: 
[pom.zip](https://github.com/schrepfler/jira-maven-plugin/files/5267355/pom.zip)

**Comment by schrepfler** [comment]
New artefact published to sonatype. Will need some time to propagate to central.

**Comment by schrepfler** [comment]
Propagated to maven central, please retest @tmortagne.

**Comment by tmortagne** [comment]
Worked great, thanks !

**Comment by schrepfler** [comment]
Thanks for confirming @tmortagne, thanks for the quick help @dgrierso!!!
